/* eslint-disable */

export enum ActionTypes {
  GET_CABLE_OPTIONS = 'GET_CABLE_OPTIONS',
  GET_EPIN_PROVIDERS = 'GET_EPIN_PROVIDERS',
  GET_CABLE_PRODUCT_LIST = 'GET_CABLE_PRODUCT_LIST',
  STAGE_CABLE = 'STAGE_CABLE',
  UNSTAGE_CABLE = 'UNSTAGE_CABLE',
}

const cableTypes = {
  GET_CABLE_OPTIONS: 'GET_CABLE_OPTIONS', STAGE_CABLE: 'STAGE_CABLE',
  UNSTAGE_CABLE: 'UNSTAGE_CABLE',
  GET_CABLE_PRODUCT_LIST: 'GET_CABLE_PRODUCT_LIST',
  GET_EPIN_PROVIDERS: 'GET_EPIN_PROVIDERS',

}


export default cableTypes;
