/* eslint-disable */

export enum ActionTypes {
  GET_AVAILABLE_GIFT_CARDS = 'GET_AVAILABLE_GIFT_CARDS',
  STAGE_GIFT_CARD = 'STAGE_GIFT_CARD',
  UNSTAGE_GIFT_CARD = 'UNSTAGE_GIFT_CARD',
  INITIATE_TRANSACTION_FLOW = 'INITIATE_TRANSACTION_FLOW',
  SEARCH_GIFT_CARD = 'SEARCH_GIFT_CARD',
  LOADING_GIFT_CARD = 'LOADING_GIFT_CARD',
  GET_CATEGORIES = 'GET_CATEGORIES',
  GET_SERVICES = "GET_SERVICES"
}

const giftCardTypes = {
  GET_SERVICES: 'GET_SERVICES',
  GET_AVAILABLE_GIFT_CARDS: 'GET_AVAILABLE_GIFT_CARDS', STAGE_GIFT_CARD: 'STAGE_GIFT_CARD', UNSTAGE_GIFT_CARD: 'UNSTAGE_GIFT_CARD', INITIATE_TRANSACTION_FLOW: 'INITIATE_TRANSACTION_FLOW', SEARCH_GIFT_CARD: 'SEARCH_GIFT_CARD', LOADING_GIFT_CARD: 'LOADING_GIFT_CARD', GET_CATEGORIES: 'GET_CATEGORIES'
}


export default giftCardTypes;
