export default {
  SET_PAGE_TITLE: 'SET_PAGE_TITLE',
  SET_REDIRECT_URL: 'SET_REDIRECT_URL',
  SET_PURCHASE_WALL: 'SET_PURCHASE_WALL',
  LOGIN_DATA: 'LOGIN_DATA',
  LOADING_PAGE: 'LOADING_PAGE',
  SET_PAGINATION: 'SET_PAGINATION'
}