const userTypes = {
  LOG_IN: 'LOG_IN',
  LOG_OUT: 'LOG_OUT',
  SET_USER: 'SET_USER',
  UPDATE_USER_PROFILE: 'UPDATE_USER_PROFILE',
  UPDATE_USER_PASSWORD: 'UPDATE_USER_PASSWORD',
  TOGGLE_LIVE_MODE: 'TOGGLE_LIVE_MODE',
  GET_WALLETS: 'GET_WALLETS',
  SET_TEMP_USER: 'SET_TEMP_USER'
}

export default userTypes;